FROM python:3.11-slim

WORKDIR /app

RUN apt-get -qq update && \
    apt-get -qq install -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Instalar dependencias del sistema
COPY docker/locale.gen /etc/locale.gen
COPY system-requirements.txt /srv/system-requirements.txt
COPY system-dev-requirements.txt /srv/system-dev-requirements.txt
RUN apt-get -qq update && \
    xargs apt-get -qq install -y < /srv/system-requirements.txt && \
    xargs apt-get -qq install -y < /srv/system-dev-requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# pipenv
WORKDIR /srv
RUN pip install --upgrade pip pipenv
COPY Pipfile* ./
RUN pipenv install --dev --system --deploy
WORKDIR /app
# end pipenv

# Copiar la aplicación
COPY src/ .
COPY docker/app.docker.ini /app/app.ini
COPY docker/app.docker.ini /srv/app.ini

# Copiar wait-for-it.sh y darle permisos de ejecución
COPY docker/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

# Copiar entrypoint.sh y darle permisos de ejecución
COPY docker/entrypoint.test.sh /entrypoint.test.sh
RUN chmod +x /entrypoint.test.sh

# Ejecutar el entrypoint
ENTRYPOINT ["/entrypoint.test.sh"]
