# https://hub.docker.com/_/python/
FROM registry.apsl.net/library/django-cookiecutter-base:2024-10-08

COPY docker/locale.gen /etc/locale.gen
COPY system-requirements.txt /srv/system-requirements.txt
RUN  apt-get -qq update && xargs apt-get -qq install < /srv/system-requirements.txt

WORKDIR /deps

COPY Pipfile* ./

CMD ["bash"]
