# https://hub.docker.com/_/python/
FROM python:3.11-bullseye

COPY docker/locale.gen /etc/locale.gen
COPY system-requirements.txt /srv/system-requirements.txt
RUN  apt-get -qq update && xargs apt-get -qq install < /srv/system-requirements.txt

WORKDIR /deps

COPY Pipfile* ./

CMD ["bash"]
