# Generated by Django 4.2.16 on 2025-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariotelegram",
            name="rate_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name="Rate Fee (%)"),
        ),
    ]
