# Generated by Django 4.2.16 on 2025-03-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot", "0002_usuariotelegram_rate_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.usuariotelegram")),
            ],
        ),
    ]
