# Generated by Django 4.2.16 on 2025-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate_fee", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Rate Fee (%)")),
            ],
        ),
    ]
