# Generated by Django 4.2.20 on 2025-03-28 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alertas_bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariotelegram",
            name="rate_fee",
        ),
        migrations.CreateModel(
            name="InvestmentWatchdog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("side", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], default="sell", max_length=4)),
                (
                    "rate_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name="Rate Fee (%)"),
                ),
                ("payment_method_id", models.CharField(default="EUR", max_length=3)),
                ("amount", models.PositiveIntegerField()),
                ("asset_code", models.CharField(default="BTC", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchdogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchdog",
                "verbose_name_plural": "Watchdogs",
                "ordering": ["-created_at"],
            },
        ),
    ]
