# Generated by Django 4.2.16 on 2025-03-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_usuariotelegram_rate_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alertas_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracion",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="configuracion",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracion",
            name="user_telegram",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="bot.usuariotelegram"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configuracion",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
