# Generated by Django 4.2.20 on 2025-03-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alertas_bot", "0002_remove_usuariotelegram_rate_fee_investmentwatchdog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentwatchdog",
            name="rate_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Rate Fee (%)"),
        ),
    ]
