# Generated by Django 4.2.20 on 2025-04-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alertas_bot", "0003_alter_investmentwatchdog_rate_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchdogNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("offer_id", models.CharField(max_length=100)),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                ("offer_details", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "watchdog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alertas_bot.investmentwatchdog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de Watchdog",
                "verbose_name_plural": "Notificaciones de Watchdog",
                "unique_together": {("watchdog", "offer_id")},
            },
        ),
    ]
