# Generated by Django 4.2.20 on 2025-03-27 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_usuariotelegram_rate_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alertas_bot", "0003_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracion",
            name="mfa_enabled",
        ),
        migrations.AlterField(
            model_name="configuracion",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="configuracion",
            name="user_telegram",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bot.usuariotelegram"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+99999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,17}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
