# Generated by Django 4.2.20 on 2025-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas_bot", "0004_watchdognotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentwatchdog",
            name="payment_method_id",
            field=models.CharField(default="51", max_length=6),
        ),
    ]
