# Generated by Django 4.2.20 on 2025-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas_bot", "0006_investmentwatchdog_usuario_telegram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracion",
            name="image",
            field=models.ImageField(blank=True, default="profile.png", null=True, upload_to="profile_pics/"),
        ),
    ]
