# Generated by Django 4.2.20 on 2025-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255, verbose_name="Pregunta")),
                ("answer", models.TextField(verbose_name="Respuesta")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pregunta Frecuente",
                "verbose_name_plural": "Preguntas Frecuentes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Categoría de FAQ",
                "verbose_name_plural": "Categorías de FAQ",
                "ordering": ["order"],
            },
        ),
    ]
