# Generated by Django 4.2.20 on 2025-04-11 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(verbose_name="Respuesta"),
        ),
    ]
