# Generated by Django 4.2.20 on 2025-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_alter_faq_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="related_questions",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="faq.faq", verbose_name="Preguntas relacionadas"
            ),
        ),
    ]
