# Generated by Django 4.2.20 on 2025-04-11 21:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_faq_related_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Respuesta"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_es",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Respuesta"),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="faq.faqcategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Pregunta"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Pregunta"),
        ),
        migrations.AddField(
            model_name="faqcategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="faqcategory",
            name="name_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
        ),
    ]
